// Suggested conversation topics for the "bring your own topic" field (duplicates removed).
const SUGGESTED_TOPICS = [
  "About Me",
  "Myself",
  "My family",
  "My friends",
  "My hometown",
  "My city",
  "My childhood",
  "My school days",
  "My college life",
  "My personality",
  "My strengths and weaknesses",
  "My daily life",
  "My typical day",
  "My weekend",
  "My routine",
  "My goals",
  "Hobbies & Interests",
  "Hobbies",
  "Free time",
  "Sports",
  "Music",
  "Movies",
  "TV shows",
  "Books",
  "Photography",
  "Cooking",
  "Gardening",
  "Gaming",
  "Travelling",
  "Fitness",
  "Art",
  "Technology",
  "Food",
  "Favourite food",
  "Indian food",
  "German food",
  "Street food",
  "Healthy food",
  "Vegetarian food",
  "Eating out",
  "Restaurants",
  "Favourite dishes",
  "Food habits",
  "Breakfast",
  "Lunch and dinner",
  "Snacks",
  "Travel",
  "Holidays",
  "My last trip",
  "My favourite trip",
  "Dream destinations",
  "Places I want to visit",
  "Travelling alone",
  "Travelling with friends",
  "Travelling with family",
  "Adventure travel",
  "Beach holidays",
  "Mountain holidays",
  "Travel experiences",
  "Travel memories",
  "Travel plans",
  "Home",
  "My neighbourhood",
  "Shopping",
  "Weekends",
  "Morning routine",
  "Evening routine",
  "Weather",
  "Seasons",
  "Public transport",
  "Social media",
  "Mobile phones",
  "Internet",
  "Daily habits",
  "Germany",
  "German culture",
  "Life in Germany",
  "Life in India",
  "Germany vs India",
  "German cities",
  "German weather",
  "Living abroad",
  "Moving abroad",
  "Working abroad",
  "Making friends abroad",
  "Learning German",
  "German traditions",
  "My expectations about Germany",
  "Happiness",
  "Friendship",
  "Family",
  "Money",
  "Success",
  "Work-life balance",
  "Artificial intelligence",
  "Future plans",
  "Dreams and ambitions",
];

/** Up to `n` labels containing `q` — earliest match position first, then shortest. */
export function suggestedTopics(q, n = 8) {
  q = q.trim().toLowerCase();
  if (!q) return [];
  return SUGGESTED_TOPICS.filter((t) => {
    const l = t.toLowerCase();
    return l !== q && l.includes(q);
  })
    .sort((a, b) => a.toLowerCase().indexOf(q) - b.toLowerCase().indexOf(q) || a.length - b.length)
    .slice(0, n);
}
